version: '3'
services:
  postgres:
    image: postgres
    environment:
      postgres_user: postgres
      postgres_password: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: